{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:  
  name: {{ .Values.name}}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storage}}
  storageClassName: {{ .Values.persistence.storageclassname}}
  volumeMode: Filesystem
{{- end }}
  

