apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name}}  
spec:
  selector:
    app: {{ .Values.label }}
  ports:
  - port: {{ .Values.service.sourceport}}
    targetPort: {{ .Values.service.targetport}}
  type: {{ .Values.service.type}}
  # externalTrafficPolicy: Local
